initial_checkpoint: "/home/data_normal/abiz/wuzhiqiang/wzq/shopee/code_v3/result/image/0601/fold-0/checkpoint/00077500_model.pth"

optimizer: 'adam'
weight_decay: 0.00001
start_lr: 0.00003
scheduler: null
arch: "efficientnet_b3"
margin: 0.2

fold: 0
batch_size: 4
out_dir: '/home/data_normal/abiz/wuzhiqiang/wzq/shopee/code_v3/result/image/0602/b3/'
