initial_checkpoint: null

optimizer: 'adam'
weight_decay: 0.00001
start_lr: 0.00003
scheduler: null
arch: 'bert'

fold: 0
batch_size: 16
out_dir: '/home/data_normal/abiz/wuzhiqiang/wzq/shopee/code_v3/result/text/0608/'
